global:
  scrape_interval: 15s # How often to check for new data

scrape_configs:
  - job_name: 'learnhub-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend-app:8080'] # 'backend-app' is the Docker Container Name